baseURL = 'https://0x-robert.github.io/'
languageCode = 'en-us'
title = 'Next-Block'
theme='hugo-PaperMod'
params:
    # defaultTheme: light
    # defaultTheme: dark
    defaultTheme: auto # to switch between dark or light according to browser theme
disableThemeToggle: true

